Repository Habuked/portal-practicas-profesionales, pull requests merged in 2025-04, with the labels that each got.

#1 feat: agregar definición de roles del proyecto
  roles.md
Labels: documentation

#35 Feature/flujo git javier
  Diagrama sin título.drawio
  flujo-git.md
Labels: documentation, Fase 1

#31 feat: agregar descripción general del sistema
  descripcion-general-del-sistema.md
Labels: documentation, Fase 2

#32 feat: agregar actores y funcionalidades
  actores-y-funcionalidades.md
Labels: documentation, Fase 2

#40 Create estilo-arquitectonico-javier
  estilo-arquitectonico-javier
Labels: documentation, Fase 3

#37 Create explicacion-cronograma-jazmin
  explicacion-cronograma-jazmin
Labels: Fase 1

#34 Evidencia Reunion 1
  Reunion 1 Evidencia.png
  Reunion 1-1 Evidencia.png
  Reunion2 Evidencia.png
  Reunion2-1 Evidencia.png
Labels: documentation, Fase 1
