Repository Habuked/portal-practicas-profesionales, pull requests merged in 2025-05, with the labels that each got.

#79 Feature/diagrama clase luis
  Caso-de-uso-Luis.md
  Reunion 1 Evidencia.png
  Reunion 1-1 Evidencia.png
  Reunion2 Evidencia.png
  Reunion2-1 Evidencia.png
Labels: diagramas

#71 Update README.md
  README.md
Labels: documentation, Fase 1

#82 Update bitacora-reuniones-Jazmin
  bitacora-reuniones-Jazmin
Labels: documentation

#66 Feature/diagrama estado evaluacion estudiante javier sanchez
  diagrama-estado-evaluacion-estudiante.png
Labels: diagramas

#67 Feature/diagrama estado notificacion javier sanchez
  diagrama-estado-notificacion.png
Labels: diagramas

#77 Feature/caso de uso luis
  Caso-de-uso-Luis.md
Labels: documentation

#87 Diagramas-secuencias-luis
  diagrama-secuencias-Secuencia-general-sistema.png
  diagrama-secuencias-autenticacion-de-usuario.png
  diagrama-secuencias-configuracion-sistema.png
  diagrama-secuencias-evaluacion-finalizacion.png
  diagrama-secuencias-generación-reporte-automatizado.png
  diagrama-secuencias-gestion-de-usuario-roles.png
  diagrama-secuencias-postulacion-estudiante.png
  diagrama-secuencias-publicacion-de-ofertas.png
  diagrama-secuencias-validacion-documentos.png
Labels: diagramas

#89 Diagrama de clase luis
  diagrama-de-clase-luis.png
Labels: diagramas

#88 Diagrama Caso de uso luis
  diagrama-de-uso-luis.png
Labels: diagramas

#91 Diagrama de componentes
  Diagrama de Componentes (3).pdf
Labels: diagramas
